assetic:
    bundles:        [ ICupPublicSiteBundle, CmfCreateBundle ]

# Doctrine PHPCR-ODM configuration
doctrine_phpcr:
    session:
        backend:
            # use Jackalope Doctrine DBAL
            type: doctrinedbal
            connection: default
            caches:
                meta: doctrine_cache.providers.phpcr_meta
                nodes: doctrine_cache.providers.phpcr_nodes
            # enable logging
            logging: true
            # enable profiling in the debug toolbar.
            profiling: true
        workspace:  default
        username:   "%phpcr_user%"
        password:   "%phpcr_password%"
    odm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        locales:
            en: [ de, fr, da ]
            it: [ en ]
            fr: [ en ]
            de: [ en ]
            es: [ en ]
            po: [ en ]
            da: [ en ]
        locale_fallback: hardcoded
        
# Jackalope Metadata and Node Cache services
doctrine_cache:
    providers:
        phpcr_meta:
            type: file_system
        phpcr_nodes:
            type: file_system

# Cmf Configuration
cmf_core:
    persistence:
        phpcr: true
        # if you want another basepath
        # basepath: /custom/basepath
    publish_workflow: false
    multilang:
        locales: [ en, it, fr, de, es, po, da ]

# Cmf Routing Configuration
cmf_routing:
    chain:
        routers_by_id:
            router.default: 200
            cmf_routing.dynamic_router: 100
    dynamic:
        persistence:
            phpcr:
                enabled: true
        templates_by_class:
            Symfony\Cmf\Bundle\SimpleCmsBundle\Doctrine\Phpcr\Page: ICupPublicSiteBundle:Page:index.html.twig
        locales: [ en, it, fr, de, es, po, da ]

sonata_core: ~

sonata_block:
    default_contexts: [cms/content/blocks]

# Cmf Create Configuration
fos_rest:
    view:
        formats:
            json: true

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        # define the filter to be used with the image preview
        image_upload_thumbnail:
            data_loader: cmf_media_doctrine_phpcr
            filters:
                thumbnail: { size: [100, 100], mode: outbound }
                